project_id = "tckynbgheicyqezqprdp"

# Edge Functions configuration
[functions.fetch-missing-attachments]
verify_jwt = true

[functions.cleanup-lead-duplicates]
verify_jwt = false

[functions.generate-quote-pdf]
verify_jwt = true

[functions.prisberegner-webhook]
verify_jwt = false